version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      non-breaking-dependencies:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"
    groups:
      non-breaking-dependencies:
        applies-to: version-updates
        update-types:
          - minor
          - patch