name: Build Release

on:
  push:
    branches:
      - release/**
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest" # for Intel based macs.
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "npm"

      - name: Install frontend deps
        run: npm ci

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Build bundles
        run: npm run tauri:build -- ${{ matrix.args }}

      - name: Upload Windows MSI installer
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-msi-installer
          path: src-tauri/target/release/bundle/msi/*.msi

      - name: Upload Windows NSIS installer
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-msi-installer
          path: src-tauri/target/release/bundle/nsis/*.exe

      - name: Upload Linux DEB package
        if: matrix.platform == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: linux-deb-package
          path: src-tauri/target/release/bundle/deb/*.deb

      - name: Upload Linux AppImage package
        if: matrix.platform == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: linux-rpm-package
          path: src-tauri/target/release/bundle/appimage/*.AppImage

      - name: Upload Apple x86 macos package
        if: matrix.platform == 'macos-latest' && matrix.args == '--target x86_64-apple-darwin'
        uses: actions/upload-artifact@v4
        with:
          name: apple-x86-macos-package
          path: src-tauri/target/x86_64-apple-darwin/release/bundle/macos/zuti.app

      - name: Upload Apple x86 dmg package
        if: matrix.platform == 'macos-latest' && matrix.args == '--target x86_64-apple-darwin'
        uses: actions/upload-artifact@v4
        with:
          name: apple-x86-dmg-package
          path: src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/*.app

      - name: Upload Apple aarch64 macos package
        if: matrix.platform == 'macos-latest' && matrix.args == '--target aarch64-apple-darwin'
        uses: actions/upload-artifact@v4
        with:
          name: apple-aarch64-macos-package
          path: src-tauri/target/aarch64-apple-darwin/release/bundle/macos/zuti.app

      - name: Upload Apple aarch64 dmg package
        if: matrix.platform == 'macos-latest' && matrix.args == '--target aarch64-apple-darwin'
        uses: actions/upload-artifact@v4
        with:
          name: apple-aarch64-dmg-package
          path: src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/*.app
